server:
  port: 8888
  context-path: /boot
  session:
    timeout:10
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url:jdbc: mysql://118.25.3.230:3306/template
    username: test
    password: Test.123
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5